### ISSUE TITLE
Working around custom attributes

### ISSUE THREAD

**Issue by ozodrukh** [FabianTerhorst/FastLayout#7]
I tried to invent this project weeks ago, but i gave up because of custom attributes support, as you started i wish i could help you in development if i find time. 

Anyway we could not support custom attributes. 
What can we do? Give an interface to call custom methods in order to setup and notify user that we don't support them overtime he mades changes in the layout

**Comment by FabianTerhorst** [comment]
@ozodrukh for custom attributes i had the idea to add converters with annotations. For example https://github.com/FabianTerhorst/FastLayout/blob/master/app/src/main/java/io/fabianterhorst/fastlayout/sample/MyLayoutConverter.java . But the reflection to init the converter class doesn´t work right now.https://github.com/FabianTerhorst/FastLayout/blob/master/fastlayout-processor/src/main/java/io/fabianterhorst/fastlayout/processor/LayoutProcessor.java#L107

**Comment by Alexander--** [comment]
> I tried to invent this project weeks ago, but i gave up because of custom attributes support, as you started i wish i could help you in development if i find time.

Same here. I have been continuously coming with all kinds of workarounds, but gave up after realising, that…
- Themes won't ever fully work because of the way attributes are processed;
- Even if you get them to work, someone would have to write mountains of boilerplate mappings for custom attributes.

All of that solely to combat AssetManager.

Nevertheless, good luck with this project.

> …for custom attributes i had the idea to add converters with annotations… But the reflection to init the converter class doesn´t work right now.

<s>@FabianTerhorst Have you considered using ServiceLoader?</s>

Forget that, I have just recalled seeing less roundabout solution in [other library](https://github.com/grandstaish/paperparcel). I will elaborate in #10.

**Comment by FabianTerhorst** [comment]
@Alexander-- have you also tried to create a XmlBlock.Parser with reflection?

**Comment by FabianTerhorst** [comment]
@Alexander-- but im sure setting a theme programatically should work. I will try to find a solution for this.

**Comment by FabianTerhorst** [comment]
@Alexander-- themes should working now.
